# Generated by Django 2.1.3 on 2018-11-11 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=200)),
                ('designer_email', models.EmailField(max_length=254)),
                ('designer_phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')])),
                ('work_title', models.CharField(max_length=200)),
                ('work_dimensions', models.CharField(max_length=200)),
                ('work_description', models.TextField()),
                ('work_display_requirements', models.TextField()),
                ('work_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be entered in YYYY format', regex='^\\d{4}$)')])),
            ],
        ),
    ]
