# Generated by Django 2.1.3 on 2018-11-11 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wipa2_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200)),
                ('work_dimensions', models.CharField(max_length=200)),
                ('work_description', models.TextField()),
                ('work_display_requirements', models.TextField()),
                ('work_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be entered in YYYY format', regex='^\\d{4}$)')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_photo', models.FileField(upload_to='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='wipa2_show.Work')),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='work_description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='work_dimensions',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='work_display_requirements',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='work_title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='work_year',
        ),
        migrations.AddField(
            model_name='work',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='wipa2_show.Submission'),
        ),
    ]
