# Generated by Django 2.1.3 on 2018-11-11 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wipa2_show', '0002_auto_20181111_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=200)),
                ('designer_email', models.EmailField(max_length=254)),
                ('designer_phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(\\+?\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='submission',
        ),
        migrations.AlterField(
            model_name='work',
            name='work_year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be entered in YYYY format', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_work', to='wipa2_show.Work'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='work_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='designer',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wipa2_show.Work'),
        ),
    ]
