# Generated by Django 2.1.3 on 2018-12-20 00:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wipa2_show.models


class Migration(migrations.Migration):

    dependencies = [
        ('wipa2_show', '0003_auto_20181111_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_email', models.EmailField(max_length=254)),
                ('artist_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(\\+?\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')])),
                ('exhibition_names', models.TextField()),
                ('exhibition_statement', models.TextField(blank=True)),
                ('artist_bio', models.TextField()),
                ('installation_instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_photo', models.ImageField(upload_to=wipa2_show.models.ExhibitionPhoto.images_directory_path)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_exhibition', to='wipa2_show.ExhibitionConfirmation')),
            ],
        ),
        migrations.AlterField(
            model_name='designer',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wipa2_show.Work'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_work', to='wipa2_show.Work'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='work_photo',
            field=models.ImageField(upload_to=wipa2_show.models.WorkPhoto.images_directory_path),
        ),
    ]
